site_name: talPor Handbook
theme: mkdocs
repo_url: https://github.com/talpor/talpor-dev-handbook/
site_favicon: images/favicon.ico
copyright: talPor Solutions 2015
pages:
- Home: index.md
- Conception: 'conception/index.md'
- Development:
  - 'Introduction': 'development/index.md'
  - 'Methodology':
    - 'Introduction': 'development/methodology/index.md'
    - 'Meetings': 'development/methodology/meetings.md'
    - 'Trello': 'development/methodology/trello.md'
    - 'Definition of Done': 'development/methodology/done.md'
    - 'Post-Mortem': 'development/methodology/post-mortem.md'
  - 'Tech Standards': 'development/tech/index.md'
- Deployment:
  - 'The Deployment Phase': 'deployment/index.md'
  - 'Continuous Integration': 'deployment/continuous-integration.md'
- Wrap-up: wrapup.md
